# Generated by Django 4.2.3 on 2023-09-11 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0003_detailemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndevice', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('problem', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(default='ทางร้านรับทราบการแจ้งซ่อมของลูกค้าแล้ว', max_length=100)),
                ('fixerdate', models.DateField(default=datetime.date.today)),
                ('idctm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.customer')),
            ],
        ),
    ]
