# Generated by Django 4.2.3 on 2023-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0006_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_market', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
    ]
