# Generated by Django 4.2.3 on 2023-09-11 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startapp', '0007_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nproduct', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(upload_to='products')),
                ('quantity', models.IntegerField(null=True)),
                ('selling_price', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgslip', models.ImageField(blank=True, upload_to='slip_img/')),
                ('idfix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startapp.fix')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.FloatField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.IntegerField(null=True)),
                ('idorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startapp.order')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('msg', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=1000)),
                ('idcus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startapp.customer')),
            ],
        ),
    ]
