# Generated by Django 4.2.3 on 2023-09-11 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0008_order_product_payment_orderdetail_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductToStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('total_price', models.IntegerField(default=0, null=True)),
                ('id_emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.employee')),
                ('name_market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrderProductToStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200, null=True)),
                ('order_quantity', models.IntegerField(default=0, null=True)),
                ('unit_price', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(default=0, null=True)),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.orderproducttostore')),
            ],
        ),
    ]
