# Generated by Django 4.2.3 on 2023-09-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0009_orderproducttostore_detailorderproducttostore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorderproducttostore',
            name='name_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.product'),
        ),
    ]
