# Generated by Django 4.2.3 on 2023-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0014_remove_orderdetail_idorder_orderdetail_sum_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='CustomerOrder',
        ),
    ]
