# Generated by Django 4.2.3 on 2023-09-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0015_rename_orderdetail_customerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='sell_price',
        ),
    ]
