# Generated by Django 4.2.3 on 2023-09-19 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0016_remove_customerorder_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
