# Generated by Django 4.2.3 on 2023-09-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0018_alter_message_idcus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='idcus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startapp.customer'),
        ),
    ]
