# Generated by Django 4.2.3 on 2023-09-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0019_alter_message_idcus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
