# Generated by Django 4.2.3 on 2023-09-19 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0020_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today, null=True)),
                ('msg', models.CharField(max_length=1000)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('idcus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startapp.customer')),
            ],
        ),
    ]
